import { fontFamily } from "tailwindcss/defaultTheme";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        destructive: "hsl(var(--destructive))",
        "destructive-foreground": "hsl(var(--destructive-foreground))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        textwhite: "var(--textwhite)",
        textbody: "var(--textbody)",
        textblack: "var(--textblack)",
        "brandlime-green": "var(--brandlime-green)",
        "brandblue-dark": "var(--brandblue-dark)",
        "brandblue-light": "var(--brandblue-light)",
        "light-green": "var(--light-green)",
        backgroundbackdrop: "var(--backgroundbackdrop)",
      },
      fontFamily: {
        sans: ["Inter", ...fontFamily.sans],
        heading: ["Inter", ...fontFamily.sans],
        "main-heading": ["main-heading", "sans-serif"],
        "normal-heading": ["normal-heading", "sans-serif"],
        "main-description": ["main-description", "sans-serif"],
      },
      fontSize: {
        "heading-h1": "var(--heading-h1-font-size)",
        "heading-h3": "var(--heading-h3-font-size)",
        "heading-h4": "var(--heading-h4-font-size)",
        "heading-h5": "var(--heading-h5-font-size)",
        "heading-h6": "var(--heading-h6-font-size)",
        "body-large-regular": "var(--body-large-regular-font-size)",
        "body-normal-medium": "var(--body-normal-medium-font-size)",
        "body-normal-regular": "var(--body-normal-regular-font-size)",
        "body-small-medium": "var(--body-small-medium-font-size)",
        "body-small-regular": "var(--body-small-regular-font-size)",
        "body-xs-medium": "var(--body-xs-medium-font-size)",
      },
      lineHeight: {
        "heading-h1": "var(--heading-h1-line-height)",
        "heading-h3": "var(--heading-h3-line-height)",
        "heading-h4": "var(--heading-h4-line-height)",
        "heading-h5": "var(--heading-h5-line-height)",
        "heading-h6": "var(--heading-h6-line-height)",
        "body-large-regular": "var(--body-large-regular-line-height)",
        "body-normal-medium": "var(--body-normal-medium-line-height)",
        "body-normal-regular": "var(--body-normal-regular-line-height)",
        "body-small-medium": "var(--body-small-medium-line-height)",
        "body-small-regular": "var(--body-small-regular-line-height)",
        "body-xs-medium": "var(--body-xs-medium-line-height)",
      },
      fontWeight: {
        "heading-h1": "var(--heading-h1-font-weight)",
        "heading-h3": "var(--heading-h3-font-weight)",
        "heading-h4": "var(--heading-h4-font-weight)",
        "heading-h5": "var(--heading-h5-font-weight)",
        "heading-h6": "var(--heading-h6-font-weight)",
        "body-large-regular": "var(--body-large-regular-font-weight)",
        "body-normal-medium": "var(--body-normal-medium-font-weight)",
        "body-normal-regular": "var(--body-normal-regular-font-weight)",
        "body-small-medium": "var(--body-small-medium-font-weight)",
        "body-small-regular": "var(--body-small-regular-font-weight)",
        "body-xs-medium": "var(--body-xs-medium-font-weight)",
      },
      letterSpacing: {
        "heading-h1": "var(--heading-h1-letter-spacing)",
        "heading-h3": "var(--heading-h3-letter-spacing)",
        "heading-h4": "var(--heading-h4-letter-spacing)",
        "heading-h5": "var(--heading-h5-letter-spacing)",
        "heading-h6": "var(--heading-h6-letter-spacing)",
        "body-large-regular": "var(--body-large-regular-letter-spacing)",
        "body-normal-medium": "var(--body-normal-medium-letter-spacing)",
        "body-normal-regular": "var(--body-normal-regular-letter-spacing)",
        "body-small-medium": "var(--body-small-medium-letter-spacing)",
        "body-small-regular": "var(--body-small-regular-letter-spacing)",
        "body-xs-medium": "var(--body-xs-medium-letter-spacing)",
      },
      borderRadius: {
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        aurora: {
          from: { backgroundPosition: "50% 50%, 50% 50%" },
          to: { backgroundPosition: "350% 50%, 350% 50%" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        aurora: "aurora 60s linear infinite",
      },
    },
  },
  plugins: [],
};